-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WIFIALR
-- -----------------------------------------------------
-- Base de Datos que almacena las tablas del Sistema de Emisión de Alertas basadas en Señales WiFi.

-- -----------------------------------------------------
-- Schema WIFIALR
--
-- Base de Datos que almacena las tablas del Sistema de Emisión de Alertas basadas en Señales WiFi.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WIFIALR` DEFAULT CHARACTER SET utf8 ;
USE `WIFIALR` ;

-- -----------------------------------------------------
-- Table `WIFIALR`.`MOVIMIENTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WIFIALR`.`MOVIMIENTOS` ;

CREATE TABLE IF NOT EXISTS `WIFIALR`.`MOVIMIENTOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MOVIMIENTO` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WIFIALR`.`ALERTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WIFIALR`.`ALERTAS` ;

CREATE TABLE IF NOT EXISTS `WIFIALR`.`ALERTAS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ALERTA` VARCHAR(200) NOT NULL,
  `FK_MOVIMIENTO` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_MOVIMIENTO_idx` (`FK_MOVIMIENTO` ASC) VISIBLE,
  CONSTRAINT `FK_ALERTAS_MOVIMIENTOS`
    FOREIGN KEY (`FK_MOVIMIENTO`)
    REFERENCES `WIFIALR`.`MOVIMIENTOS` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WIFIALR`.`MIN_MAX`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WIFIALR`.`MIN_MAX` ;

CREATE TABLE IF NOT EXISTS `WIFIALR`.`MIN_MAX` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ANTENA_1_AMP_SUB1` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB2` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB3` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB4` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB5` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB6` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB7` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB8` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB9` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB10` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB11` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB12` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB13` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB14` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB15` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB16` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB17` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB18` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB19` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB20` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB21` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB22` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB23` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB24` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB25` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB26` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB27` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB28` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB29` DECIMAL(6,4) NOT NULL,
  `ANTENA_1_AMP_SUB30` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB1` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB2` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB3` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB4` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB5` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB6` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB7` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB8` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB9` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB10` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB11` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB12` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB13` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB14` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB15` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB16` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB17` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB18` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB19` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB20` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB21` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB22` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB23` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB24` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB25` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB26` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB27` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB28` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB29` DECIMAL(6,4) NOT NULL,
  `ANTENA_2_AMP_SUB30` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB1` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB2` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB3` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB4` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB5` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB6` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB7` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB8` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB9` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB10` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB11` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB12` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB13` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB14` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB15` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB16` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB17` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB18` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB19` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB20` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB21` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB22` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB23` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB24` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB25` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB26` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB27` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB28` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB29` DECIMAL(6,4) NOT NULL,
  `ANTENA_3_AMP_SUB30` DECIMAL(6,4) NOT NULL,
  `VALOR` VARCHAR(45) NOT NULL COMMENT 'PUEDE SER \"MINIMO\" O  \"MAXIMO\"',
  `DATE_CREATED` DATETIME NOT NULL,
  `FK_MOVIMIENTO` INT NOT NULL,
  `ASOCIADO` INT NULL COMMENT 'CUANDO ES UN REGISTRO DE VALORES EN \"MINIMO\", SE DEJA VACÍO ESTE CAMPO; CUANDO ES UN REGISTRO DE VALORES EN \"MAXIMO\", ESTE CAMPO TENDRÁ EL VALOR DEL ID DE SU VALOR \"MINIMO\" ASOCIADO.\n.',
  PRIMARY KEY (`ID`),
  INDEX `FK_MOVIMIENTO_idx` (`FK_MOVIMIENTO` ASC) VISIBLE,
  CONSTRAINT `FK_MIN_MAX_MOVIMIENTOS`
    FOREIGN KEY (`FK_MOVIMIENTO`)
    REFERENCES `WIFIALR`.`MOVIMIENTOS` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
